export const OAuthSettings = {
    appId: '66878c44-bc13-4ce5-a92e-fd52f0ffd7f3',
    authority: 'https://login.microsoftonline.com/9f952c8b-5bd3-45e9-96ec-7f8b668f1537',
    redirectUri: 'http://localhost:4200',
    scopes: [
      "user.read",
      "user.read.all",
      "ChannelMessage.Read.All",
      "ChannelSettings.Read.All",
      "Channel.ReadBasic.All", 
      "ChannelSettings.ReadWrite.All", 
      "Group.Read.All", 
      "Directory.Read.All", 
      "Group.ReadWrite.All", 
      "Directory.ReadWrite.All",
      "TeamMember.Read.All",
      "TeamMember.ReadWrite.All",
      "Team.ReadBasic.All",
      "TeamSettings.Read.All",
      "TeamSettings.ReadWrite.All",
      "Group.ReadWrite.All",
      "Directory.ReadWrite.All",
      "Sites.Read.All"
    ],
  };